### ISSUE TITLE
Change links at bottom of page

### ISSUE THREAD

**Issue by janzika** [Climate-Data-Dynamics/climate-data-dynamics-lab-website#17]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://climate-data-dynamics.github.io/climate-data-dynamics-lab-website/team/

### Description

Need to update all the links at bottom of page to lab and/or Zika accounts.

**Comment by jbisits** [comment]
This can be done in `_config.yaml`

```yaml
# site social media and other links
links:
  email: contact@Climate-Data-Dynamics.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: Climate-Data-Dynamics
  twitter: Climate-Data-Dynamics
  youtube: Climate-Data-Dynamics
```

The GitHub account is correct but like you say the rest are not!
